

spring:
  mvc:
    view:
      prefix: /WEB-INF/html/
      suffix: .jsp
  aop:
    auto: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true   #消息发送到交换机确认机制,是否确认回调

  http:
    encoding:
        charset: UTF-8
        enabled: true
        force: true

server:
  port: 8180
  context-path: /demo

